sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: F1eSFgByQi8jlOhG36L6nHhZ+3M9r8OwxY42FFHk5wKkrDzHKBLzl+UiFkQRIoDN4SA1X8DKklgMglydqmK3VeEe8GvqgUVIbFSyEMjARE5seW6rTaXohgz4MVm575Orh+AT7GxBWYMptoq2yh8V/QAaryeA9aDALCxNgIhkDodNjMDSWKbkikzgzeEWUfCOyOi8G2QPcP4BoO9YM8oaQWdarz8imSMR5c1oFuW3yuud5EM3bN0TxMlar+vL58HDKPefQzQ2mE+tX02BuaLVmv312UxHa0l24w5wAK4jA3PIRscK1iQSVivJKdq7QAPIOf07I4dUHsKiXSHOX8JPU7YKibInwj5GS1Mj8ZABYQj6FZ8Atm88VRt7DnIRH1aYaGv9fECQBFyE0oJh+Fat5GHcn9GM8VIYzmJjTF4nEW3VgbXQovZ7dEvtKjv8GNKDHpBkMg0J5SH/atBHhtTf+H5r8l5oVH+vRh1/xibwcAcjAzDgj8NuAVdVkdrwBEzyx4aN4gA926W7+/nSWnEYRYxjtzD7LlRmDNe9g+sh5tGSN0a1zTMzglm8Ocr8CM8YJqMeiWm1/YcPmrXttGkTzwAb+qk1uA0qQkEydbH97RdLEX8Ph1jI2pDshU0+h68Ectu1dPmoy3vUvIcxG1+tm0U1SdGrKR4hxmQ4UZRtj/I=
  - secure: Cf7wBuztnvmKpOz1hSwZ/EpP67EKhdz2i5IIm3lf0YEnM2zGOjlEgGTOXkMlbNZmVMAMxdfkmPP8q89Jlh5Oo9x8W9U/YCwAeugaajHogxkqp7RhfmWnWVdSXvJ3Trxk5xV3hkkRFWsGrg+2dR+fVTbQBWSYpAQNVglWkE0VHeycfxGjIlrYPSvr15aOJWQH/pPVCQEFib5mrVzWIJTg0FI4B1uKTzDZHpa9hmF3ymY7bkby6TpOF2F5up9TYetm75LuRSMGAyfJjBs9oODw634MqOPHT+W7ysdDs5MjjZBMp+8oHEpkbIXcsfpoxZLj0JN3z9jilJjWG7p7XgCok+evt1YjegpZ7YPvh+CiwSiZBv/Yqpci02mui6o24y3TFnwTfdJ9O8k1iS6KkN+GNE8DGeBo1a48XQbGpUzTV3uSbvEtBYZSDMQ4d7bk+3qfk/DgwALMkYtA+aMnR3UE5X93IzkpDo18n/Sp+LCyK9KMnfRxDRLsJwFc1zS3r3nbAd1a5pQjTOYqPK93ixDXg9VlN87RB1rnIumYEgpAoYCzaVMWh6Ht5f/prrYsV7QSJbBgxhvLJT4KmsfarptAChWoIMtwNPQpTNeaKFAHXZJg+brFiN+8pRKT6lWClkCentEXY8CZ119LyJWCWYMjiUITkQ4Mt2XQVb++Sx/312M=
